--- #YAML:1.0
name: Apache-Quota
version: 0.02
author:
  - Dave Rolsky <autarch@urth.org>
abstract: |-
  Flexible transfer limiting/throttling under mod_perl
license: perl
recommends:
  BerkeleyDB: 0
  DB_File::Lock: 0
provides:
  Apache::Quota:
    file: lib/Apache/Quota.pm
    version: 0.02
  Apache::Quota::BerkeleyDB:
    file: lib/Apache/Quota/BerkeleyDB.pm
  Apache::Quota::DB_File::Lock:
    file: lib/Apache/Quota/DB_File/Lock.pm
generated_by: Module::Build version 0.23
